### ISSUE TITLE
Vérification sur les répertoires

### ISSUE THREAD

**Issue by symac** [symac/Omeka-S-module-ExtractOcr#8]
@Daniel-KM je viens de réinstaller un nouvel omeka et je voulais y ajouter ce module et j'ai un message d'erreur qui me semblait bizarre lors de l'installation du module qui m'indique sur le dossier files/temp n'est pas writable.

En y regardant de plus près j'ai l'impression que c'est lié au commit ee4cfef7599060b4619426ff51638161d12d7298 (il y a trois ans, oui c'est pas récent, dans Module.php à la ligne 301). En effet dans checkdir on va tester sir le basename est writable sans être dans le contexte donc il va nous répondre toujours non, je pense qu'en testant le dirname plutôt que le basename cela résoudrait le problème, est-ce que ça vous semble juste ?

**Comment by Daniel-KM** [comment]
Oui, c'est sans doute mieux. J'ai corrigé dans 3.4.6.
